@startuml a
title "Diagrama de clases"

package es/madrid/parla/tierno/equipo/src/diagrama{



    package src/equipo/modelo{

        package factoria{

            interface Equipable{
                + agregarJugador(jugador: Jugador): void
                + eliminarJugador(dorsal: int): void
                + jugarPartido(oficial: boolean): void
                + obtenerResumenUltimoPartido(): String
                + obtenerHistoricoTemporada(): String
                + obtenerResumenJugador(dorsal: int): String
            }

            class FactoriaJugador{
                +crearJugador(int habilidad, int altura):Jugador
            }
            class FactoriaPartido{
                +crearPartido(int opc):Partido
            }

        }
        class Equipo{
            - String: nombre
            - jugador : List<jugador>
            - partidos : Stack<Partidos>
        }


        class Jugador{
            - nombre: String
            - dorsal: int
            - habilidad: String
            - String:altura
            - puntos: int
            - faltas: int
        }
        class Alapivot extends Jugador{

        }

        class Alero extends Jugador{

        }

        class Base extends Jugador{

        }

        class Escota extends Jugador{

        }

        class Pivot extends Jugador{

        }


        class Oficial extends Partidos{
            
        }

        class Exhibicion extends Partidos{

        }


        class Partidos{

            - tipo: String {local u oficial}
            - equipoLocal: Equipo
            - equipoVisitante: Equipo

            + calcularPuntos(): void
            + calcularFaltas(): void


        }


    }


    package src/equipo/Vista{
        class App {}

    }


    Equipable <|.... Equipo
    Jugador ....o  Equipo
    Partidos ....o Equipo
    FactoriaJugador .....o Equipo
    FactoriaPartido .....o Equipo


}

@enduml