@startuml a
title "Diagrama de clases"

package es/madrid/parla/tierno/equipo/src/diagrama{
    package src/equipo/Controlador{

        interface Equipable{
            + agregarJugador(jugador: Jugador): void
            + eliminarJugador(dorsal: int): void
            + jugarPartido(oficial: boolean): void
            + obtenerResumenUltimoPartido(): String
            + obtenerHistoricoTemporada(): String
            + obtenerResumenJugador(dorsal: int): String
        }

    }


    package src/equipo/modelo{
        class Equipo{
            - String: nombre
            - jugador : List<jugador>
            - partidos : List<Partidos>
        }


        class Jugador{
            - nombre: String
            - dorsal: int
            - habilidad: String
            - String:altura
            - puntos: int
            - faltas: int
        }
        class Alapivot extends Jugador{

        }

        class Alero extends Jugador{

        }

        class Base extends Jugador{

        }

        class Escota extends Jugador{

        }

        class Pivot extends Jugador{

        }


        class FactoriaJugador(){
            + crearJugado( altura: String, habilidad: String): Jugador
                
        }


        class Partidos{

            - tipo: String {local u oficial}
            - equipoLocal: Equipo
            - equipoVisitante: Equipo

            + calcularPuntos(): void
            + calcularFaltas(): void


        }


    }


    package src/equipo/Vista{
        class App {}

    }


    Equipable <|.... Equipo
    Jugador ....*  Equipo
    Partidos ....o Equipo


}

@enduml